### PR TITLE
RPC authentication, new wallet management methods, and sweep_all

### LINKED ISSUE #9: How to specify rpc-login username/pass
It looks like there's not a way to authenticate to the new monero-wallet-rpc, am I just missing it?

### PR DESCRIPTION
**Pull request by sneurlax**
This pull request adds optional RPC authentication, new wallet management methods create_wall and open_wallet, and differentiates the old sweep method into sweep_dust and sweep_all.

It also updates the documentation in README.md, the tests in test/index_test.js, and updates the major version in package.json to 4.0.0.  All authorship, donation addresses, etc. are left unchanged.

This pull request closes https://github.com/PsychicCat/monero-nodejs/issues/9 and https://github.com/PsychicCat/monero-nodejs/issues/14

### CODE REVIEW

**Comment by sneurlax** [comment]
@PsychicCat this should close all existing issues :) I'm going to continue working on wrapping daemon methods, too.  Should I submit that as additional PRs here?

**Comment by sneurlax** [comment]
In order to bring this wrapper up to 0.12.0.0 "Lithium Luna," though, I'll likely just bring https://github.com/sneurlax/moneronodejs in wholesale.  I'll push that through to dev and open a pull request from there into master for @PsychicCat's final say, as it introduces breaking changes.  Honestly, though, this is pretty outdated by this point.

**Review by PsychicCat — APPROVED** [review]

**Comment by PsychicCat** [comment]
Merged, I can publish to NPM later today. Thanks @sneurlax.

**Comment by sneurlax** [comment]
Cheers

**Comment by sneurlax** [comment]
PS, your last commit wasn't from your PsychicCat account.  Can delete this comment after/if you want to fix that.  If you want a 0.12 "Lithium Luna"-ready library, I was planning on opening a PR from my work in https://github.com/sneurlax/moneronodejs ... but that's only if you want that.

**Comment by PsychicCat** [comment]
Thanks for the heads up. Btw, are you part of the monero integrations team? I like the efforts to coordinate things in one place. I wonder what would be the best option, in regards to the PR. I'd be happy to merge your updates in, but if that's going to end up in monero-integrations as well it seems confusing to have two repos. What do you think is best? I would be open to transferring ownership of this repo as well if that made sense.

**Comment by sneurlax** [comment]
of course, comrade :D I keep two separate accts for personal and crypto work ... will delete this too ha

**Comment by sneurlax** [comment]
yes, I'm a code monkey for monero-integrations as of two or three months ago.  serhack is lead dev / maintainer for the org and cryptochangements34 is a collaborator.  honestly I do think it would be best to consolidate things over in monero-integrations.  one issue is that the "standard" format is eg. monerogo, monerophp, moneronodejs etc ... monero-nodejs sticks out just a tad but that's just my OCD

what I'd be concerned about--if it's important to you--is finding a way to preserve your contributions officially. or is that not a priority?

**Comment by sneurlax** [comment]
monero-integrations is just so ... official. it instills confidence that it's the right tool, and it attracts more collaboration imo

one issue, though, is that so far serhack has seemed to imply that a javascript library may not be exactly needed, as https://github.com/mymonero/mymonero-core-js does everything we're doing, and more.  i'm still working on javascript because i'm using my own lib for my own project, and the structure of mymonero-core-js doesn't fit into what i'm doing (need to wrap everything with rxjs in my case.)

sorry to rant.

**Comment by sneurlax** [comment]
@PsychicCat, take a look at https://github.com/sneurlax/moneronodejs and let me know what *you'd* like to do.

As for me, I would definitely like to be a contributor to the npm package itself.  That way it can be updated at will independently of this repo.

**Comment by sneurlax** [comment]
Need to update package to 0.12 Lithium Luna: see https://github.com/monerojs/monerojs/issues/2

**Pull request merged**
