### PR TITLE
Wallet.prototype.transfers

### PR DESCRIPTION
**Pull request by amiuhle**
Support for `get_transfers` RPC method. It's undocumented, I will open a PR on `monero-site` for this.

This is related to https://github.com/PsychicCat/monero-nodejs/pull/6

Sorry about the whitespace changes, I'll remove them, should I rebase.

### CODE REVIEW

**Comment by amiuhle** [comment]
Also, I know this is kind of an extreme example, but maybe we should refactor to accept an options hash instead of individual arguments?

It would be more simple and more consistent to the actual RPC calls. I can submit a PR if you'd like.

**Comment by PsychicCat** [comment]
@amiuhle thanks for the PRs. i will review tomorrow. 

if you wouldn't mind checking out the dev-v10 branch and taking a look, that's the direction i would like to go.

**Comment by amiuhle** [comment]
> if you wouldn't mind checking out the dev-v10 branch and taking a look, that's the direction i would like to go.

Looks good. Do you want me to rebase on `dev-v10` and make some adjustments before you review?

**Comment by PsychicCat** [comment]
That would be great, thanks. My plan was to eventually merge dev-v10 up to master when all of the new RPC commands were integrated.

**Comment by amiuhle** [comment]
Well look at that, nice work in the `dev-v10` branch, `get_transfers` is already in there and you've also thought about unsigned integers! :+1: 

I'll close this PR. I might open another one with documentation once I have documented `get_transfers` on getmonero.org.

**Pull request closed without merging**
